export const styles = {
  wrap: { minHeight: "100vh", background: "#EDE9DC", fontFamily: "'Work Sans', sans-serif", color: "#1E2A33", WebkitFontSmoothing: "antialiased" },
  container: { maxWidth: 640, margin: "0 auto", padding: "24px 16px 64px" },
  tabStrip: { display: "flex", gap: 4, overflowX: "auto", marginBottom: 0, paddingBottom: 2 },
  tab: { flexShrink: 0, border: "1px solid #D3CEB9", borderBottom: "none", background: "#E2DECB", color: "#5B6670", fontFamily: "'IBM Plex Mono', monospace", fontSize: 11.5, padding: "7px 11px", borderRadius: "7px 7px 0 0", cursor: "pointer" },
  tabActive: { background: "#FBF9F1", color: "#1E2A33", fontWeight: 600, borderColor: "#D3CEB9", boxShadow: "0 -1px 0 #FBF9F1" },
  page: {
    background: "#FBF9F1",
    border: "1px solid #D3CEB9",
    borderRadius: "0 10px 10px 10px",
    padding: "26px 26px 30px",
    backgroundImage: "repeating-linear-gradient(#FBF9F1 0px, #FBF9F1 31px, #E9E5D5 32px)",
    boxShadow: "0 1px 2px rgba(30,42,51,0.04), 0 12px 28px -16px rgba(30,42,51,0.22)",
  },
  pageTopRow: { display: "flex", justifyContent: "space-between", alignItems: "flex-start" },
  pageLabel: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 11, letterSpacing: "0.09em", textTransform: "uppercase", color: "#8A8368" },
  h1: { fontFamily: "'Fraunces', serif", fontSize: 27, fontWeight: 700, margin: "4px 0 0", color: "#1E2A33", letterSpacing: "-0.01em" },
  p: { fontSize: 14, color: "#5B6670", lineHeight: 1.55 },
  stamp: {
    border: "2px solid #B0483D", color: "#B0483D", borderRadius: "50%", width: 68, height: 68,
    display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
    transform: "rotate(-9deg)", fontFamily: "'IBM Plex Mono', monospace", fontSize: 10.5, fontWeight: 600,
    letterSpacing: "0.03em", opacity: 0.9, flexShrink: 0,
    boxShadow: "inset 0 0 0 1px rgba(176,72,61,0.15), 0 2px 6px -2px rgba(176,72,61,0.3)",
  },
  stampCountdown: { border: "2px solid #2F6F62", color: "#2F6F62", boxShadow: "inset 0 0 0 1px rgba(47,111,98,0.15), 0 2px 6px -2px rgba(47,111,98,0.3)" },
  navRow: { display: "flex", alignItems: "center", gap: 10, marginTop: 16 },
  navBtn: { border: "1px solid #D3CEB9", background: "#FBF9F1", borderRadius: 7, width: 30, height: 30, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "#1E2A33" },
  navWeek: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 12, color: "#5B6670" },
  rule: { borderTop: "1px dashed #D3CEB9", margin: "18px 0" },
  sectionLabel: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 11.5, letterSpacing: "0.07em", textTransform: "uppercase", color: "#8A8368", marginBottom: 11, fontWeight: 500 },
  checklist: { listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: 10 },
  checkItem: { display: "flex", gap: 9, fontSize: 14.5, lineHeight: 1.5, color: "#1E2A33" },
  noteBox: { background: "#F3EDDD", border: "1px dashed #C7A9A0", borderRadius: 9, padding: "15px 17px" },
  noteLabel: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 11, letterSpacing: "0.07em", textTransform: "uppercase", color: "#B0483D", marginBottom: 11, fontWeight: 600 },
  siblingBox: { background: "#EAF0F3", border: "1px dashed #9FBAC9", borderRadius: 9, padding: "15px 17px" },
  siblingLabel: { display: "flex", alignItems: "center", gap: 6, fontFamily: "'IBM Plex Mono', monospace", fontSize: 11, letterSpacing: "0.07em", textTransform: "uppercase", color: "#3F6E8C", marginBottom: 11, fontWeight: 600 },
  formRow: { display: "flex", gap: 16, flexWrap: "wrap", marginBottom: 14 },
  formField: { display: "flex", alignItems: "center", gap: 7, borderBottom: "1.5px solid #C9C4AD", paddingBottom: 8, flex: "1 1 140px", minWidth: 0 },
  formFieldLabel: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 12, color: "#5B6670", flexShrink: 0 },
  formInput: { border: "none", background: "transparent", flex: 1, minWidth: 0, fontFamily: "'IBM Plex Mono', monospace", fontSize: 16, color: "#1E2A33", textAlign: "right", fontVariantNumeric: "tabular-nums" },
  formUnit: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 12, color: "#8A8368", flexShrink: 0 },
  stampBtn: { display: "flex", alignItems: "center", gap: 6, border: "1px solid #2F6F62", background: "transparent", color: "#2F6F62", borderRadius: 7, padding: "9px 16px", fontSize: 13.5, fontFamily: "'IBM Plex Mono', monospace", fontWeight: 500, cursor: "pointer" },
  saveMsg: { fontSize: 12, fontFamily: "'IBM Plex Mono', monospace", color: "#2F6F62", marginTop: 9 },
  chartsCol: { display: "flex", flexDirection: "column", gap: 24, marginTop: 20 },
  chartBox: { minWidth: 0 },
  chartFootnote: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 10.5, color: "#8A8368", marginTop: 8, lineHeight: 1.5 },
  chartTitle: { fontFamily: "'IBM Plex Mono', monospace", fontSize: 10.5, color: "#8A8368", marginBottom: 5, letterSpacing: "0.06em", fontWeight: 500 },
  blankLabel: { display: "block", fontFamily: "'IBM Plex Mono', monospace", fontSize: 11, color: "#5B6670", marginTop: 14, marginBottom: 5 },
  blankInput: { width: "100%", padding: "9px 11px", borderRadius: 7, border: "1px solid #D3CEB9", fontSize: 14, fontFamily: "'IBM Plex Mono', monospace" },
  footer: { fontFamily: "'IBM Plex Mono', monospace", textAlign: "center", fontSize: 10.5, color: "#8A8368", marginTop: 24, letterSpacing: "0.02em" },

  // ---- Auth / FamilySetup / child selector additions ----
  linkBtn: { border: "none", background: "none", color: "#2F6F62", fontWeight: 600, fontSize: 13, cursor: "pointer", padding: 0, textDecoration: "underline" },
  formGroup: { display: "flex", flexDirection: "column", gap: 4, marginBottom: 14 },
  memberRow: { display: "flex", gap: 8, alignItems: "center", marginBottom: 8, flexWrap: "wrap" },
  memberInput: { flex: "1 1 140px", padding: "8px 10px", borderRadius: 7, border: "1px solid #D3CEB9", fontSize: 13.5, fontFamily: "'Work Sans', sans-serif" },
  memberDateInput: { flex: "0 1 150px", padding: "8px 10px", borderRadius: 7, border: "1px solid #D3CEB9", fontSize: 13.5, fontFamily: "'IBM Plex Mono', monospace" },
  removeBtn: { border: "1px solid #D9A79F", background: "transparent", color: "#B0483D", borderRadius: 7, width: 32, height: 32, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flexShrink: 0 },
  addRowBtn: { display: "flex", alignItems: "center", gap: 6, border: "1px dashed #B8B096", background: "transparent", color: "#5B6670", borderRadius: 7, padding: "7px 12px", fontSize: 13, cursor: "pointer", marginTop: 2, marginBottom: 18 },
  topBar: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 14 },
  childTabs: { display: "flex", gap: 6, overflowX: "auto", marginBottom: 14 },
  childTab: { flexShrink: 0, border: "1px solid #D3CEB9", background: "#E2DECB", color: "#5B6670", fontFamily: "'IBM Plex Mono', monospace", fontSize: 12, padding: "6px 12px", borderRadius: 8, cursor: "pointer" },
  childTabActive: { background: "#2F6F62", color: "#FBF9F1", borderColor: "#2F6F62", fontWeight: 600 },
  iconBtn: { border: "1px solid #D3CEB9", background: "#FBF9F1", borderRadius: 7, width: 32, height: 32, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", color: "#5B6670" },

  // ---- Saved measurements list ----
  // ---- Photos ----
  photoThumbWrap: { position: "relative", width: 64, height: 64, flexShrink: 0 },
  photoThumb: { width: 64, height: 64, objectFit: "cover", borderRadius: 8, border: "1px solid #D3CEB9", background: "#E9E5D5" },
  photoRemoveBtn: { position: "absolute", top: -6, right: -6, width: 20, height: 20, borderRadius: "50%", border: "1px solid #D9A79F", background: "#FBF9F1", color: "#B0483D", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" },
  photoUploadBtn: { display: "inline-flex", alignItems: "center", gap: 6, border: "1px dashed #B8B096", borderRadius: 7, padding: "7px 12px", fontSize: 12.5, color: "#5B6670", cursor: "pointer", fontFamily: "'IBM Plex Mono', monospace" },

  // ---- Quick topic tips (eten/slapen/huilen) ----
  quickTipsBox: { background: "#FBF3E4", border: "1px solid #E3C994", borderRadius: 10, padding: "10px 12px", marginBottom: 12 },
  quickTipsRow: { display: "flex", gap: 8, flexWrap: "wrap" },
  topicChip: { display: "flex", alignItems: "center", gap: 6, border: "1px solid #E3C994", background: "#FBF9F1", color: "#8A5A2B", borderRadius: 20, padding: "6px 13px", fontSize: 12.5, fontFamily: "'IBM Plex Mono', monospace", cursor: "pointer" },
  topicChipActive: { background: "#8A5A2B", color: "#FBF3E4", borderColor: "#8A5A2B", fontWeight: 600 },

  // ---- Journal (verslagje per week) ----
  journalTextarea: { width: "100%", padding: "10px 12px", borderRadius: 8, border: "1px solid #D3CEB9", fontSize: 14, fontFamily: "'Work Sans', sans-serif", color: "#1E2A33", resize: "vertical", lineHeight: 1.5, background: "#FBF9F1" },
  journalMicBtn: { display: "flex", alignItems: "center", gap: 6, border: "1px solid #D3CEB9", background: "#FBF9F1", color: "#5B6670", borderRadius: 7, padding: "8px 13px", fontSize: 12.5, fontFamily: "'IBM Plex Mono', monospace", cursor: "pointer" },
  journalMicBtnActive: { background: "#B0483D", color: "#FBF9F1", borderColor: "#B0483D" },
  journalRecordingHint: { fontSize: 11.5, color: "#B0483D", marginTop: 6, fontFamily: "'IBM Plex Mono', monospace" },
};
